package com.neffapps.jazzchords.notes

import androidx.compose.ui.unit.Dp

class Fretboard {

    companion object {

        private const val baseWidth = 40.0f

        val AllFrets = listOf(
            Fret(
                0,
                listOf(
                    Note(0,1,"A"),
                    Note(0,2,"E"),
                    Note(0,3,"C"),
                    Note(0,4,"G"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                1,
                listOf(
                    Note(1,1,"Bb"),
                    Note(1,2,"F"),
                    Note(1,3,"C#"),
                    Note(1,4,"G#"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                2,
                listOf(
                    Note(2,1,"B"),
                    Note(2,2,"F#"),
                    Note(2,3,"D"),
                    Note(2,4,"A"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                3,
                listOf(
                    Note(3,1,"C"),
                    Note(3,2,"G"),
                    Note(3,3,"D#"),
                    Note(3,4,"Bb"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                4,
                listOf(
                    Note(4,1,"C#"),
                    Note(4,2,"G#"),
                    Note(4,3,"E"),
                    Note(4,4,"B"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                5,
                listOf(
                    Note(5,1,"D"),
                    Note(5,2,"A"),
                    Note(5,3,"F"),
                    Note(5,4,"C"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                6,
                listOf(
                    Note(6,1,"D#"),
                    Note(6,2,"Bb"),
                    Note(6,3,"F#"),
                    Note(6,4,"C#"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                7,
                listOf(
                    Note(7,1,"E"),
                    Note(7,2,"B"),
                    Note(7,3,"G"),
                    Note(7,4,"D"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                8,
                listOf(
                    Note(8,1,"F"),
                    Note(8,2,"C"),
                    Note(8,3,"G#"),
                    Note(8,4,"D#"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                9,
                listOf(
                    Note(9,1,"F#"),
                    Note(9,2,"C#"),
                    Note(9,3,"A"),
                    Note(9,4,"E"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                10,
                listOf(
                    Note(10,1,"G"),
                    Note(10,2,"D"),
                    Note(10,3,"Bb"),
                    Note(10,4,"F"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                11,
                listOf(
                    Note(11,1,"G#"),
                    Note(11,2,"D#"),
                    Note(11,3,"B"),
                    Note(11,4,"F#"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                12,
                listOf(
                    Note(12,1,"A"),
                    Note(12,2,"E"),
                    Note(12,3,"C"),
                    Note(12,4,"G"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                13,
                listOf(
                    Note(13,1,"Bb"),
                    Note(13,2,"F"),
                    Note(13,3,"C#"),
                    Note(13,4,"G#"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                14,
                listOf(
                    Note(14,1,"B"),
                    Note(14,2,"F#"),
                    Note(14,3,"D"),
                    Note(14,4,"A"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                15,
                listOf(
                    Note(15,1,"C"),
                    Note(15,2,"G"),
                    Note(15,3,"D#"),
                    Note(15,4,"Bb"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                16,
                listOf(
                    Note(16,1,"C#"),
                    Note(16,2,"G#"),
                    Note(16,3,"E"),
                    Note(16,4,"B"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                17,
                listOf(
                    Note(17,1,"D"),
                    Note(17,2,"A"),
                    Note(17,3,"F"),
                    Note(17,4,"C"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                18,
                listOf(
                    Note(18,1,"D#"),
                    Note(18,2,"Bb"),
                    Note(18,3,"F#"),
                    Note(18,4,"C#"),
                ),
                Dp(baseWidth)
            ),
            Fret(
                19,
                listOf(
                    Note(19,1,"E"),
                    Note(19,2,"B"),
                    Note(19,3,"G"),
                    Note(19,4,"D"),
                ),
                Dp(baseWidth)
            ),
        )
    }
}